title: 하이브레인넷 인턴 기술블로그
description: 안녕안녕
site-title: 헬로우

url: http://jhheo.github.com/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: JuhanHeo
   twitter: JuhanHeo
   facebook: JuhanHeo
   email: jhheo@hibrain.net

google_analytics: "UA-58263416-1"
